bones_yumm_homepage:
    pattern:  /
    defaults: { _controller: BonesYummBundle:Page:index }
    requirements:
      _method: GET

bones_yumm_about:
    pattern: /about
    defaults: { _controller: BonesYummBundle:Page:about }
    requirements:
      _method: GET

bones_yumm_contact:
    pattern: /contact
    defaults: { _controller: BonesYummBundle:Page:contact }
    requirements:
      _method : GET|POST
